version: "3.9"
name: projectname
services:
  projectname_nginx_default:
    container_name: projectname_nginx_default
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../src:/var/www
    links:
      - projectname_php_default
  projectname_php_default:
    container_name: projectname_php_default
    build: ./php
    working_dir: /var/www
    volumes:
      - ../src:/var/www
  projectname_db:
    container_name: projectname_db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: devpass
      MYSQL_DATABASE: marktplatz
    ports:
        - "3306:3306"
  projectname_adminer:
    container_name: projectname_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
