version: "3.9"
name: lotto
services:
  lotto_nginx_default:
    container_name: lotto_nginx_default
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../src:/var/www
    links:
      - lotto_php_default
  lotto_php_default:
    container_name: lotto_php_default
    build: ./php
    working_dir: /var/www
    volumes:
      - ../src:/var/www
  lotto_db:
    container_name: lotto_db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: devpass
      MYSQL_DATABASE: marktplatz
    ports:
      - "3306:3306"
  lotto_adminer:
    container_name: lotto_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
